### PR TITLE
Add developer tier

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by whomhasfallen — APPROVED** [review]
Nice. Good job Nicki.

**Comment by whomhasfallen** [comment]
I'll wait for Pue before merging, though.

**Review by Sodre177 — CHANGES_REQUESTED** [review]
- Developer perm func should source from a "developers" list instead of "contributors". 
- Contributors perm func should also be changed so that it inherits from developer instead of exec, now.

Otherwise looks great :)

**Comment by whomhasfallen** [comment]
Oh, yeah.

**Review by Sodre177 — APPROVED** [review]
Looks good :thumbsup:

**Review by whomhasfallen — APPROVED** [review]
Was looking through the code to check if the changes comply with Pue's "guidelines". Looks good!

**Pull request merged**
